---
name: Generate secrets
on: # yamllint disable-line rule:truthy
  pull_request_target:
    branches:
    - main
jobs:
  generate_secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Debug message
      run: |
        echo "hello asd from test2"
        echo "$GITHUB_SHA"
        echo "$GITHUB_REF"
        echo "commit: ${{ github.event.pull_request.head.sha }}"
        echo "bye from test2"
