---
name: Generate secrets
on: # yamllint disable-line rule:truthy
  pull_request_target:
    types:
    - closed
    branches:
    - main
jobs:
  generate_secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Debug message
      run: |
        echo "hello from main"
        echo "$GITHUB_SHA"
        echo "bye from main"
